src/entry/urls.py
#from django.conf.urls import patterns, url
from django.conf.urls import url, include
#from django.conf.urls.defaults import *

from .views import index, detail

app_name = 'entry'

urlpatterns = [
    url(r'^$', index, name='index'),
    # eg: /entries/5/
    url(r'^(?P<entry_id>\d+)/$', detail, name='detail'),
]

src/src/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('book/', include('book.urls', namespace='book')),
    #path('', include('entry.urls', namespace='entry')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/entry/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
class Entry(models.Model):

    class Meta:
        ordering = ['order']
        verbose_name_plural = "entries"

    def __unicode__(self):
        return self.name

    name = models.CharField(max_length=50)
    data = models.CharField(max_length=200, blank=True)
    order = models.IntegerField(default=0)

class EntryForm(ModelForm):
    class Meta:
        model = Entry
        fields = "__all__"

src/entry/views.py
#from django.template import Context, loader
from django.shortcuts import render
from django.http import Http404, HttpResponse, QueryDict
from django.template import RequestContext
from django.contrib import messages

from .models import Entry


def index(request):

    if request.method == 'POST':

        # request.POST['content'] is a query string like 'entry[]=3&entry[]=2&entry[]=1'
        # convert to a QueryDict so we can do things with it
        entries = QueryDict(request.POST['content'])

        for index, entry_id in enumerate(entries.getlist('entry[]')):
            # save index of entry_id as it's new order value
            entry = Entry.objects.get(id=entry_id)
            entry.order = index
            entry.save()

    # split our entries arbitrarily, so we can have two lists on the page...
    entry_list1 = Entry.objects.order_by('order')[:2]
    entry_list2 = Entry.objects.order_by('order')[2:]

    context = {'entry_list1': entry_list1, 'entry_list2': entry_list2}

    return render(request, 'entry/index.html', context)

def detail(request, entry_id):
    try:
        entry = Entry.objects.get(pk=entry_id)
    except Entry.DoesNotExist:
        raise Http404
    return render(request, 'entry/detail.html', {'entry': entry})

src/entry/templates/entry/index.html
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>sortable demo</title>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/overcast/jquery-ui.css">
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>

<script type="text/javascript" language="javascript">
  $(document).ready(function() {
    $("#sortable1").sortable({
      connectWith: ".connectedSortable",

      update: function(event, ui) {
        var serial = $('#sortable1').sortable('serialize');
        $.ajax({
          url: "{% url 'entry:index' %}",
          type: "post",
          data: { 'content': serial, 'csrfmiddlewaretoken' : '{{ csrf_token }}' }
        });
      },

    }).disableSelection();

    $("#sortable2").sortable({
      connectWith: ".connectedSortable",

    }).disableSelection();
  });
</script>

</head>
<body>

    <h3>Top two:</h3>
    <ul id="sortable1" class="connectedSortable">
    {% for entry in entry_list1 %}
      <li id="entry_{{ entry.id }}" class="ui-state-default">
        <a href="{% url 'entry:detail' entry.id %}">{{ entry.name }}</a>
      </li>
    {% endfor %}
    </ul>

    <h3>The rest:</h3>
    <ul id="sortable2" class="connectedSortable">
    {% for entry in entry_list2 %}
      <li id="entry_{{ entry.id }}" class="ui-state-default">
        <a href="{% url 'djsortable.views.detail' entry.id %}">{{ entry }}</a>
      </li>
    {% endfor %}
    </ul>

</body>
</html>